version: 0.2

env:
  variables:
    IMAGE_TAG: v0.0.1-53

phases:
  post_build:
    commands:
      - printf '[{"name":"gerbera-api","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
