version: '3.3'
services:
  app: &app
    build:
      context: .
      dockerfile: Dockerfile.base
    command: >
      bash -c "
        rm -f tmp/pids/server.pid
        bundle exec rails s -b 0.0.0.0
      "
    ports:
      - "3000:3000"
    environment:
      WEBPACKER_DEV_SERVER_HOST: webpacker
    volumes:
      - .:/var/app/current
  webpacker:
    <<: *app
    command: >
      bash -c "
        rm -rf public/packs
        bin/webpack-dev-server
      "
    ports:
      - 3035:3035
    environment:
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
