ARG registry
FROM ${registry}/hybitz-almalinux:8.10-20250803-29

RUN sudo yum -y install sqlite-devel

ADD Gemfile Gemfile.lock ./
RUN sudo chown -R ${USER}:${USER} ./
RUN bundle install -j2

ADD package.json yarn.lock ./
RUN sudo chown -R ${USER}:${USER} ./
RUN yarn install && yarn cache clean
