apiVersion: apps/v1
kind: Deployment
metadata:
  name: bizquest-app
  labels:
    app: bizquest-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bizquest-app
  template:
    metadata:
      labels:
        app: bizquest-app
    spec:
      restartPolicy: Always
      containers:
      - name: bizquest
        image: bizquest/app:latest
        envFrom:
        - configMapRef:
            name: bizquest-config
        - secretRef:
            name: bizquest-secret
        env:
        - name: RAILS_LOG_TO_STDOUT
          value: 'true'
        - name: RAILS_SERVE_STATIC_FILES
          value: 'true'
        - name: PORT
          value: '3000'
        command: ['bundle', 'exec', 'rails', 's']
